[package]
name = "flash-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"
tokio-util = { version = "0.7", features = ["io"] }
mime_guess = "2.0"